### ISSUE TITLE
[ FEATURE REQUEST ] - Card games

### ISSUE THREAD

**Issue by EatinBeanz** [Just-Natsuki-Team/NatsukiModDev#122]
# Overview:
[brief description of what this aims to achieve]
Being able to play poker, war, or even an oddity like hanafuda with Natsuki would be amazing! I'd love to be able to play poker with Nats for hours, there could even be cupcake or manga betting chips in place!
## Must haves:
Poker, War, Hanafuda, betting chips, and of course witty dialogue from Natty
## Could haves:
Blackjack, Rummy, Crazy Eights, Go Fish, etc.

**Comment by Blizzardsev** [comment]
Hello again,

While we do have card games in place, we'd certainly like to open up the possibility of playing more types of game with Natsuki - however, we'd like to retain a focus on simple card games, so please bear that in mind.

However, I'd like to note that implementing even a single game takes considerable effort - we have to develop the game logic, dialogue, menu/UI elements... etc. And that isn't taking into account testing and review!

Going forward, could you please restrict suggestions like this to a single game per issue? This makes things much easier to track and we don't end up writing off good concepts unnecessarily because they are bundled up with a lot of concepts we can't accommodate.

Thanks!

**Comment by EatinBeanz** [comment]
My apologies this was my first time posting a discussion. I understand completely, and I'm sorry for bombarding you with fifty million things at a time, I understand that this kind of work is not easy and definitely meticulous, I didn't mean to seem inconsiderate. I just got a bit excited and began to type whatever I could think of game wise... I'll be sure to keep ideas one subject mattered at a time from now on.
