### ISSUE TITLE
[ FEATURE REQUEST ] - New Accessories

### ISSUE THREAD

**Issue by SomeRandomGuyOrPerson** [Just-Natsuki-Team/NatsukiModDev#130]
Hello there, I thought of some new stuff that can be added for Natsuki Overhaul.

I have some ideas for what she will wear: Pink Neko Ears, Pink Sunglasses, Dye her hair to another color (from your old version of 'Just Natsuki,' Cupcake Shirt, and a Cupcake hair clip for more neat stuff that Natsuki will love for eternity.

**Comment by Blizzardsev** [comment]
Hi,

Thanks for your suggestion and apologies for the delay.

We can indeed look at adding extra accessories, outfits, etc., so long as we feel they fit with the vision of the mod. I should note that with the overhaul being a complete rework in terms of not just code/assets but vision, we should avoid borrowing concepts simply because they existed in the previous version.

A cupcake shirt and hairclip is an interesting idea; did you have any ideas as to theme, etc? For example, would the cupcake aspect on the shirt be subtle (like the cat motif on Natsuki's casual outfit), or more pronounced? Did you have any thoughts as to colours?

I think we'd prefer to avoid hair recolours, at least on an official basis. Natsuki's hair and eye colour are two of her key traits, and given the anime style's focus on those two aspects I don't think it'd serve to have Natsuki _feel_ like Natsuki. When the outfit overhaul is complete, these could still be added by users as optional extras instead.

@kkrosie123 - any thoughts on this one?

**Comment by kkrosie123** [comment]
I’ve already made some animal ears (cat and fox). She already has pink heart glasses, but I don’t think that’s what’s listed here. Cupcake shirt could be associated with the “Sugar Shirt,” but I’m assuming just a t-shirt with a cupcake decal? The hair clip I can definitely do.

**Comment by Blizzardsev** [comment]
Will be introduced in #270
