### ISSUE TITLE
how

### ISSUE THREAD

**Issue by Thepipisman** [Just-Natsuki-Team/NatsukiModDev#166]
how install

putting the files in the "game" file doesnt open the game

putting the files with all the other files makes regular ddlc

what am i doing wrong

**Comment by Blizzardsev** [comment]
Hi @Thepipisman,

It looks like you've already opened another issue on GitHub for the same problem: #160 

Please do not make repeat issues for the same problem; this does not have us look at the problem any faster and just wastes time as we have to go back and close duplicate issues just like this one now (instead of looking at the original issue).

Lastly, please note that the team works on the mod on a voluntary basis; we have our own responsibilities, hobbies and passions outside of JN and as such some patience is appreciated. Thanks!
