### ISSUE TITLE
[ BUG REPORT ] - Just Natsuki can’t open on mac 

### ISSUE THREAD

**Issue by KochiTW** [Just-Natsuki-Team/NatsukiModDev#221]
I just downloaded Just Natsuki mod and It won’t work
Yes, I have done what the git hub instructions told me, and even deleted my persistent file. But it still hasn’t work

Here’s the brief text of the trace back:
While running game code:
  File "game/definitions.rpy", line 1115, in script
    init -999 python in jn_utils:
  File "game/definitions.rpy", line 1128, in <module>
    os.makedirs(_logdir)
OSError: [Errno 30] Read-only file system: '/private/var/folders/sk/4g771ywj7mj5kpwfrn4jpp_h0000gn/T/AppTranslocation/C536E355-4FDA-47E0-889A-7EA35AAD1357/d/natsuki.app/Contents/Resources/autorun/log'

Hope someone knows how to help me fix this

**Comment by multimokia** [comment]
So, this bug is probably your Mac not liking that the game wasn't signed by an identified developer, you may want to try:
- Download vanilla DDLC and try running that one, from your desktop, the desktop is the suggested location and I never had issues there, if it works mod that one
- If it still doesn't work another approach may be required, usually under the Settings app (gear like icon) and then select security and unblock the app if it appears blocked
- Lastly the hardest way would be to run xattr on it `xattr -cr /Users/<YOUR_USER>/Desktop/DDLC.app` something like this, you'll be running that command on the Terminal app(black window icon or cmd + space and type in Terminal) for that command you'd need to change the part after the first User to the name your username is on your machine

**Comment by Blizzardsev** [comment]
Hiya @KochiTW - did you manage to get JN running using the guidance @multimokia was able to provide?

**Comment by KochiTW** [comment]
> Hiya @KochiTW - did you manage to get JN running using the guidance @multimokia was able to provide?

Ah yes, thank you, the explanation helped

**Comment by Sojann** [comment]
I can't open DDLC, there isn't any error or something but I'm clicking ,,Open'' and it don't open. Why?
