### ISSUE TITLE
[ SUPPORT REQUEST ] - Backup (question)

### ISSUE THREAD

**Issue by wowm03** [Just-Natsuki-Team/NatsukiModDev#280]
Backup: 
Recently, i downloaded this mod recommended by my friends, as i am a player of the mod 'Monika After Story', I noticed that in the wiki of JN, there's no exact instructions on ways to backup and the lack of persistent files and 'saves' in the mod folders. 
I want to know if backing up is possible for JN. If not, is it guaranteed that custom save files can back up JN completely?

**Comment by Blizzardsev** [comment]
Hi @wowm03, thank you for raising a ticket with us.

Currently, we have no save data backup mechanism: this is likely something we will look at closer to release.

However, manual backups are possible and would work in the same manner as other similar mods (copying the persistent data to another location and restoring it as required) - we can look at adding instructions on the Wiki for this.

I should note that your observation of the lack of persistent files/save data in the mod files is correct: this is because we use the standard Ren'Py save data location (differing based on OS), that is outside the installation.

**Comment by Blizzardsev** [comment]
A wiki page has now been added: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#backups-and-restores

Please let us know if you experience any issues. Thanks!
