### ISSUE TITLE
[ SUPPORT REQUEST ] - 

### ISSUE THREAD

**Issue by Siemenj** [Just-Natsuki-Team/NatsukiModDev#300]
Good evening i got a feeling mine mod miss a update bc i have seen a video whit more stuff in it

**Comment by Ionlylike1kindofcheese** [comment]
You can join the discord server to stay up-to-date here: https://discord.gg/Vf6fDZRA
You can also download the newest version with a detailed guide if you scroll down in the "<>Code" Section. There will be a description there with some information.

**Comment by Blizzardsev** [comment]
Hiya @Siemenj, thanks for raising a ticket with us.

Regarding the showcasing of mod content via YouTube: in all likelihood, those producing the videos would have modified their game data in order to progress faster/further ahead than we would intend naturally in order to have content for their videos.

In short, I wouldn't be concerned about having missed an update - this would just be content being spoiled for you ahead of time.

**Comment by Siemenj** [comment]
Oh oke thanks

Op za 14 mei 2022 22:32 schreef Blizzardsev ***@***.***>:

**Comment by Blizzardsev** [comment]
No worries!

**Comment by Siemenj** [comment]
Oké thanks

Op do 12 mei 2022 11:54 schreef Robin Vervoorn ***@***.***>:
