### ISSUE TITLE
[ FEATURE REQUEST ] - Talk

### ISSUE THREAD

**Issue by wowm03** [Just-Natsuki-Team/NatsukiModDev#301]
# Overview:
Clicking multiple times on 'talk' may trigger Natsuki being annoyed/any other feelings and reactions towards the player who made such action instead of asking if player wanted to say something to her, may be a fun idea.

**Comment by Blizzardsev** [comment]
Hiya @wowm03, thanks for your suggestion!

While I can appreciate the creativeness behind the idea, I think I'd prefer to treat this as a bugfix, since we didn't intend for players to be able to repeatedly select the same option in this manner - and although adding dialogue for something like this can be done, preventing the behaviour in the first place is a quick win and allows us to focus writing time on more anticipated features.

Thanks!
