### ISSUE TITLE
[ BUG REPORT ] - Affinity: Love/Enamored on Topics

### ISSUE THREAD

**Issue by AnimeMizuki-Weeb** [Just-Natsuki-Team/NatsukiModDev#324]
So, I don't know if it's supposed to happen or if it's a bug or something that has to do with the script on topics.
But before I reached Natsuki's affinity to love or enamored I had the topics, "Are you afraid of spiders" or "What do you think about Dan Salvato." But after I reached affinity enamored/love, those topics were removed. But I have two persistent on my Natsuki, one is when I don't say I love Natsuki, since there wasn't a topic for it in the Romance nor Natsuki section. But on my second persistent, I said that I loved Natsuki, and then I lost two of those topics, 'Are you afraid of spiders' and 'What do you think about Dan Salvato.' But when I say nothing about liking her, I don't lose the topics. I don't know why. Was this supposed to happen? Or is this a bug on the script topics?

**Comment by Blizzardsev** [comment]
Hi @AnimeMizuki-Weeb,

A number of our topics - particularly the newer ones - are unlocked based on the total amount of time spent with Natsuki (instead of, or sometimes in addition to, an actual affinity).

For the topics you've identified in particular:
- _"What do you think of Dan Salvato?"_ requires Normal affinity or higher, and that at least 48 total hours have been spent with Natsuki (I.E, with the game running).
- _"Are you afraid of spiders?"_ requires at least 24 hours or more have been spent with Natsuki (I.E, with the game running).

Whether or not this is a bug entirely depends on how you've been using your persistent files.

If you created a new persistent to experiment (the one you used to tell Natsuki you loved her), then you _wouldn't_ have the recorded playtime required to unlock those topics - regardless of affinity.

Your old persistent (where you haven't told Natsuki you love her) _would_ have the required playtime to have those two topics unlocked.

One thing I'd like to be clear on, as you mention reaching the Enamored/Loved affinity levels: please bear in mind that users are liable to forfeit their right to technical support if we suspect they've been looking to bypass/skip ahead to content, as we point out on our rules on Discord and the Wiki FAQ.

**Comment by AnimeMizuki-Weeb** [comment]
I mean that the new persistent with the one I told Natsuki that I loved her, after I told her that, those two topics were gone. So, is there something wrong?

**Comment by Blizzardsev** [comment]
Closing as per explanation given - having reviewed the topics, I can't see anything that'd cause this aside from the persistent not having the required playtime at the point of creation.
