### ISSUE TITLE
[ BUG REPORT ] - affection

### ISSUE THREAD

**Issue by keinenen** [Just-Natsuki-Team/NatsukiModDev#340]
My Nat's affection has stopped at 7.5 and won't increase further. Why so?

**Comment by Blizzardsev** [comment]
Hi @keinenen - this value doesn't determine how close you are with Natsuki directly, but is the amount of affinity/affection you can gain on a specific day.

This value is flexed (modified) based on how long you've spent with Natsuki, up to a limit: it looks to me as though you've already reached this limit, and can't go any higher - this is intentional to prevent players who have been playing the game for many months to be able to jump ahead massively compared to players who have just installed the mod (while still rewarding spending time with Natsuki!).

Given the above, I'll be closing the ticket as this is in line with what we expect. Thanks for raising a report with us and let us know if you run into any problems!
