### ISSUE TITLE
[ ART REQUEST ] - Sprite for Natsuki holding her video game console

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#395]
# Context:
For issue #394 we will need a pair of hands holding the video game console for Natsuki!

## Assets needed:
-Sprite of Natsuki's hands holding her Wintendo Twitch
-Maybe a second version to create the illusion of pressing buttons

## Caveats:
Needs to be between Natsuki and her desk

## Notes:
[Any additional information]

**Comment by Blizzardsev** [comment]
Good catch with the caveat; the issue is that we basically treat Natsuki and her desk as one sprite, so animations that move her left/right (like with the menu) work smoothly: to have the console between her body and the desk, we'd need to do some fiddly work with her sprite that'd work very differently from the other event props.

If possible, I think it'd be better that we keep the presentation like the books (so it looks like she's resting her hands over her desk) so we can easily change/hide the console without having to interact with Natsuki's actual sprite: it'd also make animating it much easier!

**Comment by Blizzardsev** [comment]
I definitely agree with the idea of having separate sprites to show her playing/tapping buttons: Ren'Py has a way we can easily put together sprites for a simple animation, so we can definitely do that!

**Comment by RaionArt** [comment]
Here a little preview of Natsuki gaming!

![Wintendo_Switch_preview](https://user-images.githubusercontent.com/112613077/189543617-cabdb437-bed8-40d9-92d0-4c95ed396f4f.png)
