### ISSUE TITLE
[ BUG REPORT ] - affection log has an error

### ISSUE THREAD

**Issue by BrandiBlitz** [Just-Natsuki-Team/NatsukiModDev#397]
I redownloaded Just Natsuki to see if a reinstallation can fix an issue with the affection log. I also got the dropfix file as an rpy: however, it just broke the affection even more. I'm at affinity 7.5. what affinity level am I able to get Natsuki to accept a love confession. I been with her since March 20, 2022. why is a beta build of JustNatsuki available to download? the beta version is what I got when I reinstalled the mod.

[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/9548711/log.txt)

**Comment by Blizzardsev** [comment]
Hi @BrandiBlitz - I've answered your question under #396.

Please don't raise multiple bug reports for the same issue - we then have to waste time responding to each one, instead of helping other people or adding more content for updates.

Regarding your beta comments: you are correct that we are in beta; we have never claimed to be a complete mod and this is mentioned clearly on the README as well as on the Wiki. The game title only changed recently to reflect this as part of our work on the next update.
