### ISSUE TITLE
[ BUG REPORT ] - No new option in Extras menu as it said in the new update

### ISSUE THREAD

**Issue by MikuMiki** [Just-Natsuki-Team/NatsukiModDev#472]
Hi, so I just opened JN up after updating it last night to the 1.01 version, I'm on WIndows 10 by the way. After talking to Natsuki and asking her questions, I checked the extras menu since it said it had a new option and I saw that another player was talking about giving her headpats in the extras menu. Well, I clicked on the extras menu and there wasn't a new option, there was only the nevermind option. Do you have to be at a certain amount of affection? because my affection with her is 52. is that why?

**Comment by Blizzardsev** [comment]
Hi @MikuMiki,

The requirement for the headpats feature is Love or higher affinity, as we outline on the wiki here: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)#extras

Until this is reached, the option will not appear: this is intentional.

You may be interested in the following documentation here on gaining affinity: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)#ways-to-gainlose-affinity

I hope this helped!

**Comment by Mikusakuradoki** [comment]
Ah I got it thank you!
