### ISSUE TITLE
[ SUPPORT REQUEST ] - How to Headpat?

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#476]
# The Problem:
I can't see the "headpat" option in the "Extra" menu. I think that Natsuki is Happy right now. Should I wait until she becomes Affectionate or is it a bug?

**Comment by RaionArt** [comment]
Hello @FastestDan and thank you for opening an issue with us.

The "headpat" option is only available on the last form of affinity levels "love", since Natsuki is a not very touchy person and you need to build up trust, before she enjoys being touched by otherwise mostly a stranger. We might add another feature with lower requirements in the future though. ;) 
If you want you can check out this wiki, which shows what you can unlock between the different affinity levels if you don't mind the spoilers:

https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-%28Spoilers%29

I hope I could help you and this is defintely not a bug, but intended.
