### ISSUE TITLE
[ BUG REPORT ] - natsuki not taking down the holiday deco?

### ISSUE THREAD

**Issue by mayday-mayjay** [Just-Natsuki-Team/NatsukiModDev#505]
# Overview:
i've been informed that natsuki takes down the deco 24hrs after the holiday event. it's been almost 2 days since christmas, i've open/closed JN plenty in that time and the deco is still up

## Replication steps:
i honestly don't know, since there hasn't been anything stick out from standard gameplay that i've done

## Additional information:
windows 10, happy aff tier

**Comment by Blizzardsev** [comment]
Hi @mayday-mayjay , can you please send over your persistent file? You can attach it here if you place it in a zip file.

**Comment by mayday-mayjay** [comment]
yep sure, here ya go

[persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10310995/persistent.zip)

**Comment by Blizzardsev** [comment]
Hi @mayday-mayjay, thanks for your patience.

I'm unsure if this issue has resolved itself for you, but as a heads-up: we are introducing a new topic that will allow players to ask Natsuki to take down any decorations in the room, if any are up. We haven't seen your issue replicated with other players, so we would consider this fixed in the next update.

Thank you for raising this with us.
