### ISSUE TITLE
[ FEATURE REQUEST ] - Option to ask Natsuki about how she's feeling.

### ISSUE THREAD

**Issue by EmeraldTheDingo** [Just-Natsuki-Team/NatsukiModDev#534]
# Overview:
I think it'd be cool to add an option to ask Natsuki about how she's feeling that day. The aim is to add another level of interaction with her and make her feel more human.

## Must haves:
Well she'd need to have a bunch of answers to pull from that is set once a day.

## Could haves:
It'd be cool to have her answers change in tone based on affinity level (I.E negative tiers would have her upset and negative most of the time. normal and tiers close would have her more indifferent and higher tiers would have her happier and more optimistic.)

## Is this feature request related to a problem? Please describe.
No, just a nice little QoL change.

**Comment by trapsena** [comment]
vouch

**Comment by RaionArt** [comment]
Hello @EmeraldTheDingo and thank you for opening an issue with us!

As much as I like this idea, after talking with team members we came to the conclusion that sadly a system like this wouldn't be worth the effort. To include an option like this we would need to create a whole system around it. Otherwise it wouldn't make sense if Natsuki tells you she is sad/down, but will light up as soon as you gift her something or talks about a topic she really enjoys! It would come off as moodswings.
The other way would be to only include really basic responses, which wouldn't justify the thoughtful writing we have otherwise in the mod and would come off as hollow or generic.

So as much as I would like to include an idea like the one you suggested, the trouble of generating a system around it is outweighing the benefits. 
Still thank you again for opening this issue, maybe we can include something like this at another time!
