### ISSUE TITLE
[ BUG REPORT ] - I did what I was supposed to do to update the mod. But for some reason it's still the 1.0.2 version. Can I get help?

### ISSUE THREAD

**Issue by OreoZone23** [Just-Natsuki-Team/NatsukiModDev#540]
# Overview:
I replaced the game, lib and update folder with the newer version. But as soon as I launched the game, it's still from the last version.

## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Blizzardsev** [comment]
Hi @OreoZone23 - can you please send a screenshot of the contents of your `game` folder?

**Comment by OreoZone23** [comment]
![Capture (3)](https://user-images.githubusercontent.com/125333342/218698130-71b9eddf-d037-41f9-8a1c-b22b58a03223.PNG)
![Capture (4)](https://user-images.githubusercontent.com/125333342/218698136-aff91907-b0af-434e-90f0-c99f829c1b2e.PNG)
![Capture (5)](https://user-images.githubusercontent.com/125333342/218698142-d53d2de3-b402-4316-98e7-454db9e60f53.PNG)
![Capture (6)](https://user-images.githubusercontent.com/125333342/218698151-d1c6d176-4ec3-4dc7-b7dc-c59b9849e0be.PNG)

Like this?

**Comment by Blizzardsev** [comment]
Okay, it's as I thought. You previously downloaded source files of the mod instead of the 1.0.2 release. When you launched DDLC.exe, these overwrote the 1.0.3 files you added, basically reverting you back to 1.0.2: this is why we always recommend installing/updating from the release files only so this can't happen.

You will need to delete your `game` folder, redownload the latest release, then paste the `game` folder from the release into your DDLC installation.

**Comment by Blizzardsev** [comment]
Also, I would note that another hotfix is likely today, so you may wish to hold off until that has been released: we'll make an announcement as well as update you here on the ticket when that happens.

**Comment by Blizzardsev** [comment]
No worries!

**Comment by Blizzardsev** [comment]
Hi @OreoZone23 and @AmartaniGitHub - that hotfix has been released. Please download the latest release and follow the update steps again to resolve your issue, if you haven't already.
