### ISSUE TITLE
[ SUPPORT REQUEST ] - When opening the game it states "A problem has occurred. Please contact JN staff.

### ISSUE THREAD

**Issue by XCloudsX** [Just-Natsuki-Team/NatsukiModDev#545]
# Overview:
[brief description of the issue(s) you are facing]
When I tried updating to 1.0.3 it showed a screen stating "A problem has occurred. Please contact JN staff."
## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]
<img width="1440" alt="Screenshot 2023-02-14 at 8 39 29 PM" src="https://user-images.githubusercontent.com/125427196/218926463-30de0086-0b56-4ca4-87ec-6c08cd957f3a.png">

**Comment by Blizzardsev** [comment]
Hi @XCloudsX - please send your persistent forward so we can look into it. You will need to attach it here inside a zip archive so GitHub will allow it to be uploaded.

**Comment by Blizzardsev** [comment]
Also, could you please send through your log file? It should be under the log folder.

**Comment by XCloudsX** [comment]
I will do it tommrow because it is still currently night for me

**Comment by XCloudsX** [comment]
OK, I will send it right now
Here:
[Persistent and Log.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10750774/Persistent.and.Log.zip)

**Comment by XCloudsX** [comment]
Oh, and I forgot to say that I am on Mac

**Comment by Blizzardsev** [comment]
Hi @XCloudsX, thanks for sending your persistent through.

From looking at your file, I can see your save data failed an integrity check, meaning that unusual game progression was found.

For example, we aim for players grow close enough to Natsuki to be able to successfully confess over a number of months: you began playing on the 8th of February of this year, with only 33 total visits recorded: this is simply not possible through legitimate means.

As this is expected behaviour given the scenario, I will be closing this ticket. If you wish to play Just Natsuki again, you will need to create a brand new save file by deleting your persistent: you may find the location by following the instructions [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent).

Thank you!
