### ISSUE TITLE
[ FEATURE REQUEST ] - Memory card game

### ISSUE THREAD

**Issue by Amazingpotato917** [Just-Natsuki-Team/NatsukiModDev#580]
# Overview:
You could play memory with Natsuki, She could go to the side like how she does in snap, shuffles the cards and lays them out, you would each take turns, and if you get a match you would get to go again.

## Must haves:
the back of the cards would be the same as snap, but they would have pictures from ddlc on there, like Natsukis cupcake, Yuris book, pictures of the girls etc.

## Could haves:
A easy, medium and hard selection, easy would be less cards, and hard would be more cards.

**Comment by Blizzardsev** [comment]
Hi @Amazingpotato917, thanks for raising an issue with us.

This is a cute idea, and I like the thought of having different DDLC cues for the card pictures - my concerns here would be introducing this new set of cards, and the simplicity of the game/how the game rules would work.

Regarding introduction of the cards: when Natsuki reveals Snap, she already mentions that she always had a set of playing cards in her desk - however, these are standard cards that could have come from anywhere: where would these new cards come from? Would she have drawn them? Etc.

Regarding the simplicity of the game: I would personally consider Snap to be the lowest skilled game Natsuki would play, and it fills a similar area (just matching cards) - if we were to introduce more games, I would personally prefer to introduce games that increase in complexity that match how she says she doesn't know many card games (like 21, or Go Fish) rather than making another game at the same/lower skill level.

Lastly, I understand that the player and Natsuki would both get a chance to see the cards at the start - how well would this scale with increasing numbers of cards? Would the player get "peeks" they can use? How would Natsuki's "memory" work? We'd also have to think about how we'd scale the UI to achieve the difficulty levels you have in mind here, which seems like a lot to invest for something close to Snap in terms of mechanics/skill as mentioned.

Overall, while I appreciate the cute ideas here, I think it's just too close to Snap with too many technical challenges to be really worthwhile, at least right now - games generally take a lot of investment, and if we're going to do that I would prefer to make something more challenging and different for our players that shows off Nat learning more things.

@RaionArt @Obsidian-Knife thoughts?

**Comment by Amazingpotato917** [comment]
Jeez more went into this then I thought, sorry, hmmm, maybe she could find them in the space room somewhere and we can explain to her how to play? If she doesn't know how, I was just thinking of an easy game because she didn't know many card games, if you guys would have to sacrifice other stuff for this then nvm, I didn't know how difficult programming games would be (don't mean that in a mean way)

**Comment by RaionArt** [comment]
My biggest fear is how visible the memory game would be when played in windows mode. Multiple cards would clutter the game, especially if we still want to have Natsuki visible too! 

Of course all the pairs would need to be drawn, which isn't really a problem, but time consuming for sure.

Additionally I also see some plotholes previously mentioned by Blizz. I'm totally open to introduce new games and will be totally ready to draw something for it! But since  the programming is the hardest part I feel like Blizz should have the last word in it.

**Comment by Blizzardsev** [comment]
I think given the above, this is something we're going to have to pass up at this stage. Thank you for your suggestion - it's always appreciated!
