### ISSUE TITLE
[ FEATURE REQUEST ] - Option to thank Natsuki.

### ISSUE THREAD

**Issue by VendixDilan** [Just-Natsuki-Team/NatsukiModDev#649]
# Overview:
Since we've a way to Apologize, i thought a way to _thank_ her would be nice too!

## Must haves:
A option to thank  Natsuki through the Menu.

## Could haves:
Similar to the Apology option, based on what she said earlier, you can thank her for different things like her pro advices.

**Comment by RaionArt** [comment]
I don't think it would be worth it to have a "thank you" option to the same level as an "apology", since the apology is connected to multiple other functions! There are only a few ways the player could be thankful towards Natsuki.

Nonetheless this could work as an admission. The player could mention they are feeling grateful for an example and depending on other factors and of course the affinity level Natsuki could react in certain ways, maybe even realizing it is about thanking her.

**Comment by RaionArt** [comment]
As this case would fall into #593, I will close this issue as it would be a double.
