### ISSUE TITLE
[ FEATURE REQUEST ] - "How are you?" topic

### ISSUE THREAD

**Issue by ElsenIsCute** [Just-Natsuki-Team/NatsukiModDev#662]
Perhaps there could be a "How are you?"/"Are you okay?" topic. Natsuki could have different responses based on affection, and if there's a plausible reason to do that.

Like for example, there could be a variable that is set to "True" whenever Natsuki finishes talking about a topic which is sensitive, for example, talk_realizations_other_girls, or similar venting topics. At the end of these it could set the variable to true (though reset this back to False after a certain amount of time) and if it is set to True once the "How are you?" topic is selected, Natsuki could have different dialog, and maybe have that dialog be affection-based too.

If you really want to go silly, you could also add different variables depending on what topic it is. Like for example talk_realizations_other_girls could set a certain variable, and the "How are you?" topic could be more specialized to that if the variable is true.

I hope that makes sense! Thanks for reading!

**Comment by gorillagrip** [comment]
I second this. It would give the player something to do without idling or repeating questions.

**Comment by Blizzardsev** [comment]
This is an interesting concept, but there is a *lot* of potential for this to grow legs and run away: realistically, the most practical would be to have some kind of mood system as you've discussed, but then we run into the problem of her response being generic and not really appropriate at all times - it would have to be in order to account for _any_ scenario she could feel a certain way: sad as a result of a conversation, or happy from an event, or angry from something getting on her nerves, etc.

The alternative would be to have a bespoke reaction for specific topics, but then we're committing ourselves to a lot of work as the topic would basically become a required update for any topic that ends on anything but a neutral note - we'd be spending a lot of time adding to a single topic whenever we add a new one that has any kind of emotional aspect. Most new topics have variations based on affinity too, so we'd also need to consider how *strong* her feelings would be when asked relative to that, which gets complicated quickly.

We also have the issue of scope creep here: if we added the option to ask how Nat feels after closing a conversation, what about:
- Events: surely she'd be annoyed after reading her Ren'Py book, or embarrassed after being caught napping?
- Admissions (if the player says they feel sad, sick, etc.)
- Apologies

Something else to think about is when the "mood" expires: it would be bizarre for Nat to still feel embarrassed after something in the morning when the player has kept her around until the evening without asking her.

I think ultimately, it's not a bad idea at all: but it comes with a lot of baggage that isn't really practical right now, at least from my point of view.

@RaionArt thoughts?

**Comment by RaionArt** [comment]
Adding to Blizz points, I feel like the biggest issue along side all the work, would be to give Natsuki non generic answers. We wouldn't want her to just answer with "I'm sad" and that's it, but at the same time we couldn't write another mood for every "sad topic". The player would want to know *why* she is upset.

Also what happens if she *is* sad at the moment and next you choose a fun topic to talk about, would her moods just switch? 

If Natsuki is angry or sad she probably wouldn't talk as much? What would be the playing experience if you just have an annoyed Natsuki sitting in front of you? 

So in theory it seems like a good idea, but the more you think about how to *actual* work on this system, there are many flaws.

**Comment by Blizzardsev** [comment]
Going to close this off, at least for now - as explained, something like this has a lot of nuance associated with it, and we can't really justify the investment needed to make something we'd be happy with out of it at this time.
