### ISSUE TITLE
[ FEATURE REQUEST ] - More idles

### ISSUE THREAD

**Issue by Megalonumber0ne** [Just-Natsuki-Team/NatsukiModDev#677]
# Overview:
Natsuki found more stuff to do when her player isn't interacting with her.

## Must haves:
Natsuki watching/playing something on a laptop (like watching anime for example), when she's at love stage, her daydreaming while looking towards the player (with the love heart emote n such)

## Could haves:
Looking into a mirror, making sure she looks okay, looking disgruntled at something like maths equations, 
One I thought would be cool was she could be all flirty like in some of her animations, but just _more_?

**Comment by RaionArt** [comment]
Hello @Megalonumber0ne and thank you for raising an issue with us!

Tbh there is already an idle animation with a laptop planned (I even drew the laptop already), so you're lucky in that regards.

With the daydreaming at love tier you mean not the idle animation, in which the player interrupts her, but the idles just between? Because the idle animations are something to trigger when Natsuki assumes the player is away or busy, so she tries to do stuff by herself as she is an independent person. Looking directly at the player would be against that purpose.

Do you have an idea how we could visualise her looking into a mirror? I feel like it would look odd to have her looking down to it and we cannot change her whole pose (I also needed to scrap one of my ideas because of that ;-;)

Math equations could be interested. Natsuki already shown  dislike to math, but I could see her keep trying.

The last one about being flirty I already explained before. I think it could be included to the "normal" idles, but we would like to focus on expanding the content for early players as this seems to be the biggest issue with JN at the moment.

**Comment by Megalonumber0ne** [comment]
I was skeptical about the mirror one actually working properly, but I decided to add it just in case it could

**Comment by RaionArt** [comment]
Laptop and math attempts idle will be introduced in v1.3.
