### ISSUE TITLE
[ FEATURE REQUEST ] - Simplified how are you topic

### ISSUE THREAD

**Issue by ElsenIsCute** [Just-Natsuki-Team/NatsukiModDev#717]
I requested a How are you topic and it was declined due to the fact that if her mood would change depending on dialog topics, there would need to be a new "how are you" topic made for everything that could potentially change her mood. So why don't we just change it so that it's simply based on her affection?

She'd have a different response for if she's at RUINED, BROKEN, DISTRESSED, UPSET, NORMAL, and so on.

But, something that could potentially be added would be her saying she's tired if it's night. Again, this "I'm tired" response would change depending on affinity.

Although this would take some time to write, it'd be easier to do than the much more complicated mood system I proposed.

**Comment by ElsenIsCute** [comment]
Also, potential addition: If it's night and they ask "How are you?" but then stay with Natsuki the whole night she would still be tired, because I can imagine pulling an all nighter and Natsuki saying she's tired, but the moment it hits morning she says she's feeling alright, so maybe do that and have it only reset when you say goodbye.

**Comment by Blizzardsev** [comment]
Going to have to refer back to our [response](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/662#issuecomment-1538175001) on the previous issue you raised for this, I'm afraid.

As we noted beforehand, it isn't _just_ an issue of complexity: it's about making dialogue that is interesting and lends real personality to Natsuki: distilling this down to only focus on one aspect of Natsuki (her closeness to the player) doesn't really help, and in my mind would magnify the problem.

Here's some scenarios to better illustrate what I'm getting at here:

- Natsuki is at the `LOVE` affinity, but she's just exited a dialogue where she is angry at the player for calling her a bad nickname. Based solely off affinity, Natsuki would give the impression that everything is perfectly fine and she's just happy to be with you! This would feel jarring and strange considering how upset she gets over being called something nasty.
- Natsuki is at the `AFFECTIONATE` affinity, and the player has just admitted to Natsuki that they feel sick. Based off affinity, Natsuki would just respond saying she feels in a good mood with none of the concern a player would expect her to have for them, which would feel odd given how concerned she was.
    - _"W-wait. How **I** feel? Now just hold on a minute, player! Don't think making this about me is going to help you!"_
- Natsuki is at the `NORMAL` affinity, and the player has just caught her reading a book she likes, embarrassing her. Based off affinity, Natsuki would respond saying she feels okay/a little bored instead of feeling embarrassed.
- Natsuki is at the `HAPPY` affinity, and the player has just finished playing Snap with her. Based off affinity, Natsuki might just say she's bored.

You can see where I'm going with this!

All of the above situations require something beyond just an affinity check in order to feel convincing and non-robotic: and those are just a tiny number of examples I pulled out of my head! We could build checks and exceptions in for these cases of course... but then we're looping right back to where we started (and the questions I asked last time).

Of course, we wouldn't have to be all or nothing - but a big part of our goals with our current writing style is to keep the player engaged and have a reason for them to explore and experience what we've written: if the dialogue is always going to be the same filler content whenever the option is used, and Natsuki is ultimately always going to feel X for Y affinity, what would be the point in asking the question?

Ultimately, I'm afraid it's going to be a no from me personally at this stage. Again, I understand the merit to the idea, but generic sounding dialogue becomes stale fast, and if we're going to do something as open ended as this then I'd want to take the time to work it all out and do it properly as I mentioned in the last issue.

@RaionArt Has your opinion changed since?

**Comment by RaionArt** [comment]
No, it didn't change.

The same problems still remain and I feel like Blizz already gave enough examples, which show the problem of introducing a system like this. 
Additionally we would still need to resort to generic dialogue to cover all moods fitting to the dialogue, which will get boring really quickly and doesn't add much to the experience.
