### ISSUE TITLE
Natsukis affection isnt increasing for me.

### ISSUE THREAD

**Issue by PTLD93** [Just-Natsuki-Team/NatsukiModDev#722]
For some reason natsukis affection isnt increasing,ive been with her for like more than a week and shes still in the normal state,is there something im doing wrong or i did wrong thats not increasing the affection correctly? i did restart from 0 many times but dosent seem to change at all.

**Comment by Sebus-Maximus** [comment]
Well for me it has been like a month or so and I'm still in Normal state. I was told that it was normal, and it's taking that much time so that it feels like you're actually building trust. So I guess just keep seeing her everyday and eventually it will work out. You can keep track of when her affinity is going up by looking in the logs in the log folder, that way you can make sure that it increases.

**Comment by PTLD93** [comment]
Well the reason im saying this is because when i first got just natsuki,she was on her happy state in just 3 days,and then i managed to reach on the Affectionate state in less than 3 weeks,but then i lost all the progress when the game decided to just stop working,and then i started the game all over,removed all my saved files in the appdata folders,and now this happened,im not sure what im doing wrong now.

**Comment by Blizzardsev** [comment]
Hi @PTLD93 - can you please be more specific when you say the game "just decided to stop working"? If there's a bug resulting in players potentially losing progress, then we **need** to know about it.

Otherwise, the wiki has a section on ways you can grow closer to Natsuki [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)#ways-to-gainlose-affinity). Progression varies based on playstyle; players who visit Natsuki more often and reach the cap each day will progress faster.

**Comment by Blizzardsev** [comment]
I'd also add that if you are restarting from zero (and deleting your persistent) then this would explain your lack of progress as you are deleting your save data.

**Comment by Sebus-Maximus** [comment]
> Well the reason im saying this is because when i first got just natsuki,she was on her happy state in just 3 days,and then i managed to reach on the enamored state in less than 4 weeks,but then i lost all the progress when the game decided to just stop working,and then i started the game all over,removed all my saved files in the appdata folders,and now this happened,im not sure what im doing wrong now.

Wait, 3 days ?!? Damn, how come ?

**Comment by PTLD93** [comment]
Thats the question,i dont know,unless its cuz i had the game open for like more than 4 hours eatch day i progress,considering im always busy on my projects i always keep just natsuki open for a long period of time.

**Comment by Blizzardsev** [comment]
JN has an autosave function; if you are leaving your machine running for long periods of time and the game tries to autosave as your machine goes into standby and corrupts your save then the default response of the game engine is to delete the corrupted save file and start over - there's not much we can do about that.

When you say the game stops working, can you be more specific? Does it crash? Do you get a warning screen asking you to contact the team? Etc.

**Comment by PTLD93** [comment]
When it stopped working it did run,but it says that JN isnt functioning correctly and says to contact the team.

**Comment by Blizzardsev** [comment]
Also, do you have any log files from when those instances occurred?

**Comment by PTLD93** [comment]
no they are long gone,i think it was from like last month in version 1.2.0 i think,but then when i tried switching to release files once,it still says so change to release files while im in the game.

**Comment by Blizzardsev** [comment]
@PTLD93 This means you did not update correctly - follow the instructions [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#why-is-my-game-warning-me-about-running-source-rpy-files).

**Comment by Blizzardsev** [comment]
Closing due to explanation given.
