### ISSUE TITLE
[ FEATURE REQUEST ] - More dialogues while away from Natsuki

### ISSUE THREAD

**Issue by SteelAxleVII** [Just-Natsuki-Team/NatsukiModDev#776]
# Overview:
[Hi there. So far the JN mod is going well, but this isn't really much of an issue, but something for this mod might need more of. I like how Natsuki's messages you through the notification box depending on what site you're on/software you're currently running. I'm not sure if I noticed, but it would be cool to have her message in a different tone based on her affection level. Or in other cases instead of seeing the same dialogues.]

(If so, I'm assuming this will be part of a future update)

**Comment by Blizzardsev** [comment]
Thanks for your suggestion. We can look at some small tweaks based on affinity, but at this stage I don't think a rewrite of the activity system in order to support specific affinity tiers or other criteria is really on the cards: and given how activity-based notifications are gated by requiring Affectionate or closer either way, reworking the system for two tiers doesn't feel like the best application of our team's time right now.
