### ISSUE TITLE
[ SUPPORT REQUEST ] - Installation on MAC

### ISSUE THREAD

**Issue by RPGee7** [Just-Natsuki-Team/NatsukiModDev#799]
@ Overview:
hello, i tried installing this mod on mac first with the JN installer file, but i was only able to extract a text document file from the zip. i was also missing the updates folder when i tried installing it manually after i found out that there was no application in the installer zip

**Comment by Blizzardsev** [comment]
Hi @RPGee7 - if you right click the file from the ZIP after downloading the installer, then you should be presented with the option to install it. Otherwise, open the terminal in the folder where the installer has been downloaded and enter `./jn-installer-mac`: you may need to modify the permissions first using `chmod u+x jn-installer-mac`.

The updates folder should not be of consequence, but is included in the current release: it should have been included when performing a manual installation according to the instructions [here](https://github.com/Just-Natsuki-Team/NatsukiModDev#manual-installation).

**Comment by Blizzardsev** [comment]
Also, you may need to review your security settings for the mod to run after installation: please see [this ticket](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/221#issuecomment-1066030620).

**Comment by RPGee7** [comment]
after running the code and selecting the ddlc app itself to install the files in, it works. thank you so much for your help 🙏
