### ISSUE TITLE
[ BUG REPORT ] - v1.3.2 Downloading failure

### ISSUE THREAD

**Issue by AnimatorGamers** [Just-Natsuki-Team/NatsukiModDev#832]
# Overview:
When downloading v1.3.2 using the installer, I got this error message, making me unable to play the most recent version.
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/66534197/65415012-579e-4381-929b-3b14387bc0b7)

## Replication steps:
This happens everytime I try to download the latest update with the installer, when the downloading bar is around half-way filled. I also tried re-installing the installer but the issue still persists.

## Additional information:
I'm using Windows 11. I'm updating JN from v1.2.4 to v1.3.2. The installer version is v0.3.0. I made sure that the game and my file explorer are both closed during the downloading.
Thank you in advance!

**Comment by Blizzardsev** [comment]
Hi @AnimatorGamers - I've just used the installer on an existing installation of JN and have not been able to replicate your issue. Your error indicates that the installer is unable to download any updates from GitHub due to the connection timing out rather than a bug with the installer itself. Given the lack of reports around problems of this kind, this would suggest the problem lies with your connection.

Can you please verify the following:

- Check that you can access the GitHub page for the latest release through a web browser
- Check that your machine has stable access to the internet before and while the installer is running
- Check that access to the network for the installer is not being blocked (I.E firewall rules, network access policies)

If the installer still fails to run, you may still update manually using the steps outlined on the README [here](https://github.com/Just-Natsuki-Team/NatsukiModDev#manual-update).

**Comment by AnimatorGamers** [comment]
Thank you for the advices!
It was indeed my internet connection that was meeting pretty high latency. Just Natsuki v1.3.2 is now downloaded and installed succesfully!
Best regards,
- Animator
