### ISSUE TITLE
[ BUG REPORT ] - Game crashed in custom outfit creator

### ISSUE THREAD

**Issue by luigicrafter** [Just-Natsuki-Team/NatsukiModDev#839]
# Overview:
The game crashed when I chose the QT sweater in the custom outfit creator.

## Replication steps:
- Ask Natsuki to create a new outfit
- Choose "QT sweater" for clothes
- Crash

## Additional information:
I run on kali-linux 6.5
Just Natsuki version 1.3.3
Full traceback: https://pastebin.com/aEE02T3w

**Comment by Blizzardsev** [comment]
Hi @luigicrafter - I don't seem to be able to replicate the issue on Windows. Can you please confirm whether this is the case with any other outfits, or just the QT sweater specifically?

**Comment by luigicrafter** [comment]
It seems to be only the QT Sweater, everything else seems to work.

**Comment by Blizzardsev** [comment]
Can you please try downloading the latest release [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/releases/tag/v1.3.3), then extract the resulting ZIP file and copy the _mod_assets_ folder into the _game_ folder of your installation (confirming any overwrite prompts) before relaunching and trying again?

**Comment by luigicrafter** [comment]
I tried that. It still crashes when I select the Qt sweater.

**Comment by Blizzardsev** [comment]
We'll investigate further and let you know when we have something.

**Comment by Blizzardsev** [comment]
Hi - sorry for the delay. The issue is related to how Linux file paths are case-sensitive, and that the QT sweater is the only vanilla outfit with assets containing capitalised text.

If you navigate to the `game/mod_assets/natsuki` folder and rename the following, then you should be able to use the sweater as intended:

- `clothes/jn_clothes_QT_sweater` -> `clothes/jn_clothes_qt_sweater`
- `sleeves/jn_clothes_QT_sweater` -> `sleeves/jn_clothes_qt_sweater`

We'll look at working in a patch.
