### ISSUE TITLE
closing game bug

### ISSUE THREAD

**Issue by globobombastico** [Just-Natsuki-Team/NatsukiModDev#850]
I found a very curious bug: when you are in the Talk menu, if you click the x several times to exit the game, you can exit the game without Natsuki getting angry and she doesn't even mention it, I don't know if it's something important I mean it's a bug but I feel like it's too strange

**Comment by globobombastico** [comment]
Besides, there is a chance that Natsuki will react and if you press the nervermind option the game will get stuck forcing you to exit the game, I would send videos but this page only leaves 10mb Bruh

**Comment by Blizzardsev** [comment]
Hi @globobombastico - regarding the behaviour of the game when the close option is used repeatedly: this is operating system behaviour that we can't do much about; we can look at some extra logic to check if the game wasn't exited cleanly but there isn't much we can do otherwise.

Can you please clarify the steps you took to get stuck when selecting "Nevermind"? A video isn't necessary, just a description of the actions taken as I don't seem to be able to replicate this behaviour.

**Comment by globobombastico** [comment]
having explained it well when first you click on the talk option or directly press the t key then when the game screen is not in full screen if you repeatedly click on the x to close the game the game will close without you Natsuki gets angry or without the log saying that the affection has decreased, and sometimes when you press the x repeatedly, what can happen is that she does react but if you press  the nervermind option to avoid closing the game abruptly the game will stay stuck without any option appearing, forcing you to exit the game

**Comment by globobombastico** [comment]
https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/153331709/f1f2abd3-508a-432b-aaff-c3e3ff6b34bb

WTH

**Comment by globobombastico** [comment]
I literally closed the game without saying goodbye and I never lowered my affinity and Natsuki didn't even mention it or in the apologize option there was the option to apologize for leaving the game

PD: the other bug I mentioned almost never comes out and is rare, so I don't have a video for that one.

**Comment by Blizzardsev** [comment]
Hi @globobombastico - the issue regarding Natsuki not tracking when the game has been force closed has already been identified with a potential fix; your issue with the "Nevermind" option resulting in a freeze is much more concerning to us as we cannot replicate it.

If you could please keep an eye on your gameplay and fill us in with any contextual information (for example, when did you try to force quit? While idling/doing nothing? While in a conversation/game? Etc.), it would go a long way.

Lastly, I've noticed you're running the source code version of the game. As the warning and our releases state, we do **not recommend** players run the source code version unless they know what they are doing. Is this intentional, and have you made any modifications to your installation?

Please note that we do not offer support to those running modified installations.

**Comment by globobombastico** [comment]
First of all, no, I have not made a single modification to the game, it is just as the game is, I just installed it from the source code version, and second, while I was trying to see if the bug that I said about the game being softlocked would come out, I discovered another strange bug in which if you click twice on nervermind literally all kinds of things happen such as events on a black screen that then give you the option to enter or that the game restarts directly with the  intro music, I'm going to send a video about it that so that it is more noticeable

**Comment by globobombastico** [comment]
and when the bug happens that I forcefully close the game it happens in two situations or when you are in the menu to talk to him either about how I feel, to apologize, to talk about something and etc. and it also happens when you are in a normal conversation, and how I already said the bug that the game is softlocked happens when you are already in a group of conversations, that is, when you already clicked on i feel, etc etc, and as I already said, no, I have not modified the game, it is the base game but downloaded of the source code version

**Comment by globobombastico** [comment]
https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/153331709/6328d002-5ba1-418d-a17e-2bf6148c5e2c

I am sending the first bug I reported again but in the launcher version and not in the source code version so you can see that I am not lying

**Comment by globobombastico** [comment]
https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/153331709/45d1313f-cde4-4b77-999b-4d1776d78d64

WTH and if you see it is the normal version

**Comment by globobombastico** [comment]
https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/153331709/c6762ef1-9e5e-4276-b7db-95f7cc44fb04

and this is a continuation of the bug

**Comment by globobombastico** [comment]
and when you click on it, instead of opening the pause menu, the game's saved menu appears without being modified, so I don't know if this is something very relevant, but I think it's a pretty serious bug that seems strange to me that no one has discovered it.

**Comment by globobombastico** [comment]
and after that music begins to play that was removed from the game and is only in the game files of the original DDLC, I don't know if that was done on purpose but I feel that such strange things happen that it is most likely that it is a bug

**Comment by Blizzardsev** [comment]
This will be resolved in the next patch.

**Comment by globobombastico** [comment]
> This will be resolved in the next patch.
ok 👍
