### ISSUE TITLE
[ BUG REPORT ] - Opened it one day and my progress was reset

### ISSUE THREAD

**Issue by FergusonGorg** [Just-Natsuki-Team/NatsukiModDev#865]
I opened the application one day and all my progress got reset. It showed the warning about the game and how its not affiliated and all that stuff and then replayed the intro sequence all over again. I was like 5 months in so i lost quite allot and im not sure how i could get it back or even if i could. It was not even the first time i opened it that day, it worked normally in the morning but when i opened it again it had reset. Is it possible to restore my progress? it looks like it went over my normal persistent and found a firstrun file created on the day of the reset. any help to get my progress back is greatly appreciated.

**Comment by RaionArt** [comment]
Hello, 

could you please attach your log file, that is inside the log folder?

**Comment by FergusonGorg** [comment]
The log got reset as well, when i opened it to see what had happened it showed the same stuff it did when i started the mod months ago, and there is nothing before it as well. i can attach my current log if you'd like but it nothing seems to be out of the ordinary with it.

**Comment by HypnoHypno** [comment]
Did you check the log outside of the log folder?

**Comment by FergusonGorg** [comment]
Not sure what to look for in there, should i attach that one?

**Comment by HypnoHypno** [comment]
sure

attach them both, there might be something.

**Comment by Blizzardsev** [comment]
Hi @FergusonGorg - do you have any persistent backups you can revert back to? We always encourage our users to back up their persistent regularly and with every new update to JN. If so, then you can simply copy a backup and replace the fresh persistent. Based on the age of the backup you may lose some progress, but this is better than starting over entirely.

Failing this, based on your operating system you may have further options. If you are on Windows, you may wish to see if File History for your persistent folder (usually found under _AppData/Roaming/RenPy/JustNatsuki_) has any older versions of itself you can roll back to: alternatively, you can see if any backups were made by Windows that include the folder that you can use.

Unfortunately outside of these options, your persistent is most likely non-recoverable; this is because in the event Ren'Py finds a persistent that it deems corrupted, the default action is to completely overwrite the persistent with a brand new one to allow the game to run - reasons for corruption can range from multiple copies of the game being launched, to the game being forcibly closed, or the system powering down while the game is trying to save/autosave.

**Comment by FergusonGorg** [comment]
i think i have a copy of the persistent somewhere, how exactly would i go about replacing the one i have with the copy?

**Comment by Blizzardsev** [comment]
Hi @FergusonGorg - if you navigate to the location where you can originally find your persistent, then just copy in your backup and select Yes if you are prompted to replace/overwrite it; make sure JN is closed before doing this.

Once you've replaced the persistent, attempt to load JN as you would normally.

As a reminder, you can find your persistent using the instructions [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent).

**Comment by FergusonGorg** [comment]
Thanks so much! Got it back to close to where i was. thanks again!

**Comment by RZed01** [comment]
> Thanks so much! Got it back to close to where i was. thanks again!

Should probably close this since it has been solved
