### ISSUE TITLE
[ FEATURE SUGGESTION ] - Have Natsuki say something for you

### ISSUE THREAD

**Issue by RZed01** [Just-Natsuki-Team/NatsukiModDev#871]
# Overview:
The idea for this feature is that you could have Natsuki say things and pose for you. Kind of like the DDLC Dialog Generator, but with only the JN sprites.

## Must haves:
-A feature that allows you to provide your own text and the pose for each snippet of text

## Could haves:
-The ability to save speeches, or do multiple back to back "panels", so to speak.

## Is this feature request related to a problem? Please describe.
This was the result of two things- the first being Friends of Monika's Say Something submod for MAS, and the second being the somewhat limited amount of topics available. Creating your own topics with this feature may help stave off the repetition somewhat.

## Potential problems/drawbacks:
The fact that this suggestion was the result of me really liking the Say Something submod. I understand that Just Natsuki is aiming to provide a different experience than MAS, so introducing a feature that exists in MAS as a submod may take away "one of the main selling points of MAS." Not to mention that implementing such a feature may result in plagiarism accusations from Friends of Monika (the creators of that submod), as I feel that this is kind of stealing their idea. Because of this, I feel that this is a suggestion that would most likely get turned down (and I fully understand if it does get rejected). That being said, as I am only supposed to suggest new features on here rather than on the Discord, I am posting this on here to see your thoughts on the matter.

**Comment by RaionArt** [comment]
Hello @RZed01 and thank you for your suggestion.

We have a couple of reasons to deny this request, but mostly because of the potential abuse this feature can provide.

To ensure people wouldn't abuse it by saying Natsuki all weird type of things, we would need to add a massive filter, which could ruin the experience before it's even available. Also from a immersion pov why would Nat be okay to say all type of things? Wouldn't she question *why* you want her to say this quote specifically?

Even when breaking down the idea to have Natsuki only strike a pose, it comes down to the same problems and adds a few more. No one can control Natsuki's feelings or emotion, she cannot be angry of sad on command and she definitely isn't the type to act this way either. Of course her idles reflect her emotions connected to the affinity tier as well. So it could rob people off the experience to see the expressions, when they are actually displayed in the game.

Adding to that is also the plagiarism you already mentioned.

**Comment by RZed01** [comment]
I can definitely see your reasoning here. It shows how Natsuki is different from Monika.
