### ISSUE TITLE
[ FEATURE REQUEST ] - Cooking mini game

### ISSUE THREAD

**Issue by AnnaLairos** [Just-Natsuki-Team/NatsukiModDev#875]
# Overview:
Adding mini game where you can cook with Natsuki (or maybe just a recipe book from her, like book with jokes but with recipes). It can be both cooking with Natsuki in game (like a mini cooking simulator) or where Natsuki cooking by herself and player repeat it step by step irl. It could look like comics or chibi mini game or full-height sprite of Nats cooking.

## Could haves:
- Maybe a kitchen/cooking club room where Natsuki will cook + perhaps cooking tips from Natsuki here and there.
- There might be scenes where she ends up with bad result, because of not good enough recipe or where she uses notebook and recipe books in her free time just to fix/improve some stages of the recipes she messed up in. Or maybe even creating her own recipes with simple sketches of desserts she'd want to make.

**Comment by RaionArt** [comment]
Hello @AnnaLairos and thank you for your suggestion.

Adding a recipe book with some simple recipes might be possible, but everything else would just be way too much time focuses on something that is supposed to be a mini game! 

Especially if you consider we would have to draw every outfit possible for the extra sprite, also who will provide the kitchen background? How did she even suddenly leave the classroom and ended up in a kitchen to cook? 
Overall your idea is big enough to be considered a game in itself rather than just a minigame for a mod focused on a visual novel!
Of course we would also need to count in what Ren'Py can even provide, given it's a programming language made for vn as well.

**Comment by AnnaLairos** [comment]
Oh, alright, I understand. I just thought that knowing Natsuki, she'd probably miss baking a lot. But if it's not doable in the game, it's okay. Thank you for the reply anyway!
