### ISSUE TITLE
[ FEATURE REQUEST ] - "Games" button.

### ISSUE THREAD

**Issue by AnnaLairos** [Just-Natsuki-Team/NatsukiModDev#876]
# Overview:
Since there's already two games (and maybe might be added more in future), games button might might be removed from "Let's talk about --> Games" to just "Games" in main menu

**Comment by RZed01** [comment]
That's kind of like how Monika After Story deals with minigames.

**Comment by RaionArt** [comment]
Hello @AnnaLairos and thank you for the suggestion.

I feel like with two games available it is still easy to navigate to them without getting lost and we also try to let the player have as much engagement with Nat as possible, which includes having actively a conversation with her.

This might be an option we could think about once we added more games, but I don't think it will be any time soon.

**Comment by AnnaLairos** [comment]
Understandable! Thank you for the answer

**Comment by Blizzardsev** [comment]
Adding to this, something to remember is that with games there is also the information and context we have to consider around those games. For example, a player that hasn't played Blackjack in a while and wasn't familiar with the game before JN might not remember the rules.

Rather than having Natsuki ask the player if they need a reminder every time they play (or after a gap in playing), it makes more sense to condense those into a dedicated game menu instead of splitting them.

In the interrim and as we don't currently have plans for more games for the time being, I'll be closing the issue for now - we can revisit this if we reach the point our game roster makes it more prudent.
