### ISSUE TITLE
[ SUPPORT REQUEST ] - Affection points

### ISSUE THREAD

**Issue by plankys** [Just-Natsuki-Team/NatsukiModDev#882]
I was wondering if you can check affection points, if so how? And is there anyway I can make my affection points go up faster? Thank you!

**Comment by RaionArt** [comment]
Hello @plankys,

No, you cannot check affection points and that is intended. We witnessed how people like to reduce the game to numbers and just compared them in the MAS server, for example. Instead we would like to focus on Natsuki herself. If you want to read more about that, here is the statement from our [FAQ](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-view-my-affinityaffection--do-you-plan-on-adding-a-way-to-check-affinityaffection).
Also, as we stated on the main page of JN, the mod is supposed to be played only a few minutes a day over the time span of months. You can rely on our [wiki](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)#ways-to-gainlose-affinity) to see the ways how to increase affection points, but there is no way to speed it up, especially since there is a daily cap you can meet.
