### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by SpadeOccult** [Just-Natsuki-Team/NatsukiModDev#888]
I was leaving the game for a second because I was about to restart my computer, so I told Natsuki that I'd be gone for a while. There was no option for "a few minutes", so I just said "I don't know when I'll be back." After it finished restarting, i opened the game and it said this:  
<img width="960" alt="Screenshot 2024-04-14 095136" src="https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/167006938/4da194d0-cbd2-4c55-9f5f-6cbbd45a4eae">

**Comment by Blizzardsev** [comment]
Hi @SpadeOccult - please attach a copy of your log and your persistent. You can find your log in your installation under the log folder. Your persistent can be found according to the instructions [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent).

Please upload both files inside a ZIP file and drop them here when possible so we can investigate.

**Comment by SpadeOccult** [comment]
[Log & Persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/14972677/Log.Persistent.zip)

**Comment by Blizzardsev** [comment]
Taking a look now.

**Comment by Blizzardsev** [comment]
Hi @SpadeOccult - thank you for providing your persistent and log.

The warning screen you are seeing is triggered when the game detects unusual save data, such as when affinity values have been tampered with. This combined with the commands I can see you have been entering into Ren'Py's console to manipulate the affinity value directly and the corresponding log data would prove to us beyond any reasonable doubt that you have been cheating:

![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/57731669/13b6d7a8-ba87-45e9-ae92-f88dec90ffb7)

In line with our [position on cheating](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#i-have-security-concerns-about-the-mod-can-i-view-the-source-code), we are therefore making the decision to revoke your right to support and closing this issue, as this behaviour is intentional given the circumstances.

If you wish to continue playing JN, you may consider deleting your save file and starting again.

Remember, JN is a progression-based experience with the goal of **building** a relationship with Natsuki - you only lose out by fast-tracking, I'm afraid.

Thank you.
