### ISSUE TITLE
[ BUG REPORT ] - 

### ISSUE THREAD

**Issue by loveNatsuki** [Just-Natsuki-Team/NatsukiModDev#898]
# Overview:
[brief description of the bug, and the impact created]
<img width="862" alt="捕获" src="https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/169278798/757f9306-e222-4189-ab7e-64af565a6577">
I was forced to change the computer time because of some computer issues, but why did this happen when I reopened it?I've reinstalled multiple times but nothing worked
## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]
After the computer time was modified, I turned on Just Natsuki and heard the music to find that Natsuki was gone
## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]
It may be related to the time of the computer modification

**Comment by RaionArt** [comment]
Hello @loveNatsuki,

Natsuki does warn you the first time if you fiddle with your time settings. She points out that you should never do that again or there might be consequences like shown above. If you were just forced to change the time, because of some issues, there would've been no reason to open JN in the meantime and she wouldn't have reacted to it.

This is no bug as we don't tolerate any form of cheating. Feel free to clear your save file and start a new story with Natsuki. You just need to delete your persistent file found [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent).
