### ISSUE TITLE
[ SUPPORT REQUEST ] - Backup saves accidentally deleted

### ISSUE THREAD

**Issue by ShinKiio** [Just-Natsuki-Team/NatsukiModDev#915]
# Overview:
As I was cleaning my appdata as I do occasionally to remove undesired files or for storage, it seems I also accidentaly deleted the backup saves for JN, which never happened before so I'm still confused as to how it happened. When I started DDLC yesterday (which was also when I cleaning my folder), the mod was back to its original state when it is played for the first time.

As much as I'd like it to be false, I think there is no way to get my long time progress back, at least as far as I know which is why I am reaching out. If there appears to be no way to get it back at all, I'm wondering if an advanced pre-made save file could perchance be shared somehow. As much as I really enjoy the mod, seeing that I have to restart from nothing stings, and I'm well aware I'm the cause of that, that is entirely my fault. I'm just hoping if there is any way out of restarting from zero.

## Additional information:
I did search in appdata, roaming, RenPy and any possible backup saves, but there is only the one from starting the game after the, I assume, erasure of the actual progress i've made in time.

Not certain if this next information is relevant but there is nothing in the "DDLC/game/saves" file either ![delete4](https://github.com/user-attachments/assets/0850eb7f-6e55-4f37-9d22-70334c0ab5d6), there is everything else from my progress outside of that folder, the items i've unlocked, etc, but the actual save file, which I am certain that is something I did not touch.
In case backup save files have nothing to do with the main save file, then I am completely confused as to why I've lost all the progress.

If any additional information is needed, I'll be happy to oblige.

**Comment by RaionArt** [comment]
Hello @ShinKiio,

Issues like these are the reason why we encourage players to do actual backups of their save files. You didn't lose your "backup", you lost your save file (the persistent file), because you _didn't_ make any back ups to begin with.

We don't provide any advanced save files, so sadly there is little that can be done here. 
Also yes, you can only find your persistent file via appdata. The folder in ddlc has nothing to do with the way JN is saved.

If you do decide to start from new, I can only point out once again, that it is a wise decision to make backups of your persistent file from time to time and to save it somehwere else, on an usb-stick for example.
